### ISSUE TITLE
Clean up readme file for spelling errors

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/friendly-markdown-intro#1]
I'm terrible at spelling, please help clean up my readme

**Comment by stephwright** [comment]
Hi Joey!  I love <3 doing copyediting.  Okay with you if I work on this issue? -Steph

**Comment by stephwright** [comment]
Hi Joey!  I <3 copyediting and checking spelling.  Okay with you if I take lead on this issue? -Steph

**Comment by joeyklee** [comment]
Hello Steph, thanks so much for your interest. I'd be delighted for you to take the lead on this. Please let me know what I can do to support you. It would be great if you could Fork the repository and make a pull request with your changes. Many many thanks! ❤️

**Comment by stephwright** [comment]
Great!  I will fork it now and get back to you with a pull request later!  Thanks, Joey! 🙇

**Comment by joeyklee** [comment]
Thanks so much Steph - I will assign you to the issue now. Looking forward to seeing those changes.

**Comment by joeyklee** [comment]
Closing issue now - many thanks Steph 🎉💪❤️
